#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Clinics.MySQLModels;

namespace Clinics.MySQLModels	
{
	public partial class ClinicsMySQLContext : OpenAccessContext, IClinicsMySQLContextUnitOfWork
	{
		private static string connectionStringName = @"ClinicsMySqlConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public ClinicsMySQLContext()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public ClinicsMySQLContext(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public ClinicsMySQLContext(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public ClinicsMySQLContext(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public ClinicsMySQLContext(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Specialiststatistic> Specialiststatistics 
		{
			get
			{
				return this.GetAll<Specialiststatistic>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of ClinicsMySQLContext.
		/// </summary>
		/// <param name="config">The BackendConfiguration of ClinicsMySQLContext.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IClinicsMySQLContextUnitOfWork : IUnitOfWork
	{
		IQueryable<Specialiststatistic> Specialiststatistics
		{
			get;
		}
	}
}
#pragma warning restore 1591
