#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Clinics.MySQLModels	
{
	public partial class Specialiststatistic
	{
		private int _idSpecialistStatistics;
		public virtual int IdSpecialistStatistics
		{
			get
			{
				return this._idSpecialistStatistics;
			}
			set
			{
				this._idSpecialistStatistics = value;
			}
		}
		
		private string _specialist;
		public virtual string Specialist
		{
			get
			{
				return this._specialist;
			}
			set
			{
				this._specialist = value;
			}
		}
		
		private string _procedure;
		public virtual string Procedure
		{
			get
			{
				return this._procedure;
			}
			set
			{
				this._procedure = value;
			}
		}
		
		private int? _procedureCount;
		public virtual int? ProcedureCount
		{
			get
			{
				return this._procedureCount;
			}
			set
			{
				this._procedureCount = value;
			}
		}
		
		private string _totalPrice;
		public virtual string TotalPrice
		{
			get
			{
				return this._totalPrice;
			}
			set
			{
				this._totalPrice = value;
			}
		}
		
		private int? _month;
		public virtual int? Month
		{
			get
			{
				return this._month;
			}
			set
			{
				this._month = value;
			}
		}
		
		private int? _year;
		public virtual int? Year
		{
			get
			{
				return this._year;
			}
			set
			{
				this._year = value;
			}
		}
		
	}
}
#pragma warning restore 1591
