//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinics
    {
        public System.Guid ClinicId { get; set; }
        public string ClinicName { get; set; }
        public string ClinicAddress { get; set; }
        public string ClinicPhones { get; set; }
        public System.Guid ClinicChief { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Specialists Specialists { get; set; }
    }
}
