//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicsProgram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MsSQLServerEntities : DbContext
    {
        public MsSQLServerEntities()
            : base("name=MsSQLServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clinics> Clinics { get; set; }
        public virtual DbSet<Manupulations> Manupulations { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Procedures> Procedures { get; set; }
        public virtual DbSet<Specialists> Specialists { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Titles> Titles { get; set; }
    }
}
