//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicsProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manupulations
    {
        public System.Guid ManupulationId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid SpecialistId { get; set; }
        public System.Guid ProcedureId { get; set; }
        public System.DateTime Date { get; set; }
        public string Information { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual Procedures Procedures { get; set; }
        public virtual Specialists Specialists { get; set; }
    }
}
