//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicsProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedures
    {
        public Procedures()
        {
            this.Manupulations = new HashSet<Manupulations>();
        }
    
        public System.Guid ProcedureId { get; set; }
        public string Name { get; set; }
        public string ISCCode { get; set; }
        public decimal Price { get; set; }
        public string Information { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Manupulations> Manupulations { get; set; }
    }
}
