//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicsProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialists
    {
        public Specialists()
        {
            this.Clinics = new HashSet<Clinics>();
            this.Manupulations = new HashSet<Manupulations>();
            this.Titles = new HashSet<Titles>();
        }
    
        public System.Guid SpecialistId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Duty { get; set; }
        public int Title { get; set; }
        public System.Guid Specialty { get; set; }
        public string UIN { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Clinics> Clinics { get; set; }
        public virtual ICollection<Manupulations> Manupulations { get; set; }
        public virtual Specialties Specialties { get; set; }
        public virtual ICollection<Titles> Titles { get; set; }
    }
}
