//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicsProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialties
    {
        public Specialties()
        {
            this.Specialists = new HashSet<Specialists>();
        }
    
        public System.Guid SpecialityId { get; set; }
        public string Speciality { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Specialists> Specialists { get; set; }
    }
}
